[package]
name = "algorithms_in_rust"
version = "0.1.0"
authors = ["Wenhao Ni <niwenhao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
